spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 38186765372-58c8k28t16sk1f0mflmqf1ndlggncqik.apps.googleusercontent.com
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email