spring.application.name=garage
# persistance.type=ddbb
# persistance.type=map
# persistance.type=array

ddbb.url=sqlite:db.sqlite
ddbb.user=testUser
ddbb.password=testPassword

# DataSource Configuration
spring.datasource.url=jdbc:sqlite:db.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate / JPA Configuration
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none

# SQLite specific: Fixes issues with connection pools
spring.datasource.hikari.maximum-pool-size=1

springdoc.swagger-ui.path=/swagger-ui
# Cambiar la ruta donde se genera el JSON de OpenAPI
springdoc.api-docs.path=/api-docs